apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test2
    app.kubernetes.io/part-of: test-application
  name: test2
  namespace: sdouglas1
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: test2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: test2
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:sdouglas1-test2
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
